version: '3'
services:
  rabbitMq:
    image: rabbitmq:3-management
    container_name: rabbitMq_container
    
  dtu-pay-service:
    image: dtu-pay-api-service
    container_name: dtu-pay-api-service
    ports:
     - "8080:8080"
    
  token-service:
    image: token-service 
    container_name: token-service

 
